PYTHON_VERSION="3.12.1"
COMPOSE_FILE=docker/docker-compose.yml
LOCAL_COMPOSE_FILE=docker/docker-compose.local.yml
DOCKER_COMPOSE=docker compose -f $(COMPOSE_FILE)

BLACK        := $(shell tput -Txterm setaf 0)
RED          := $(shell tput -Txterm setaf 1)
GREEN        := $(shell tput -Txterm setaf 2)
YELLOW       := $(shell tput -Txterm setaf 3)
LIGHTPURPLE  := $(shell tput -Txterm setaf 4)
PURPLE       := $(shell tput -Txterm setaf 5)
BLUE         := $(shell tput -Txterm setaf 6)
WHITE        := $(shell tput -Txterm setaf 7)
RESET := $(shell tput -Txterm sgr0)

default: run

#==============================================
# Setting up the local development environment
#==============================================
dev-check: ## Check to make sure pyenv and virtualenv are installed
	@echo "Checking for pyenv"
	@pyenv --version 2> /dev/null || echo "${YELLOW}pyenv not installed${RESET}"
	@echo "Checking for virtualenv"
	@pyenv virtualenv --version 2> /dev/null || echo "${YELLOW}virtualenv not installed${RESET}"
	@echo "Checking for Python version $(PYTHON_VERSION)"
	@pyenv versions | grep $(PYTHON_VERSION) 2> /dev/null || echo "${YELLOW}python version $(PYTHON_VERSION) not installed${RESET} - run ${RED}pyenv install $(PYTHON_VERSION)${RESET}"

dev-setup: ## Create virtual environment
	@make dev-check
	@echo "Creating virtual environment named 'yaml_to_qti'"
	@pyenv virtualenv $(PYTHON_VERSION) yaml_to_qti || echo "Virtual environment 'yaml_to_qti' already exists"
	@pyenv local yaml_to_qti
	@echo "Installing Python dependencies"
	@pip install -r ./requirements-dev.txt
	@echo "Installing pre-commit hooks"
	@pre-commit install

dev-remove: ## Remove virtual environment
	@pyenv uninstall yaml_to_qti

dev-setup-local: ## Install application dependencies to run local development Flask server
	@pip install -r ./app/requirements.txt

run-local: ## Start a local Flask development server on your own machine
	@flask --app=./app/main.py --debug run

#================================================================================
# Managing the Docker environment (e.g. starting, stopping, deleting containers)
#================================================================================
start: start-attached ## Start the app in a Docker container (default: attached mode)
start-dev: start-dev-attached ## Start the app in a Docker container (default: attached mode) in reload mode

start-attached: ## Start the app in a Docker container attached to the current terminal
	@echo "${GREEN}Starting app containers in attached mode${RESET}"
	$(DOCKER_COMPOSE) up

start-dev-attached: ## Start the app in a Docker container in reload mode attached to the current terminal
	@echo "${GREEN}Starting app containers in attached mode${RESET}"
	$(DOCKER_COMPOSE) -f $(LOCAL_COMPOSE_FILE) up

start-daemon: ## Start the app in a Docker container in daemon mode
	@echo "${GREEN}Starting app containers in daemon mode${RESET}"
	@echo "Run \`make start-attached\` to run in attached mode, or view container logs with \`make logs\`"
	$(DOCKER_COMPOSE) up -d

start-dev-daemon: ## Start the app in a Docker container in reload mode and in daemon mode
	@echo "${GREEN}Starting app containers in daemon mode${RESET}"
	@echo "Run \`make start-attached\` to run in attached mode, or view container logs with \`make logs\`"
	$(DOCKER_COMPOSE) -f $(LOCAL_COMPOSE_FILE) up -d

stop: ## Stop the running Docker containers without removing them
	@echo "${YELLOW}Stopping app containers${RESET}"
	$(DOCKER_COMPOSE) stop

clean: ## Stops and removes Docker containers
	@echo "${YELLOW}Stopping and removing app containers${RESET}"
	$(DOCKER_COMPOSE) stop

clean-volumes: ## Stops and removes Docker containers and volumes
	@echo "${YELLOW}Stopping and removing app containers and purging existing volumes${RESET}"
	$(DOCKER_COMPOSE) down -v

clean-volumes-images: ## Stops and removes Docker containers, volumes, and built Docker images
	@echo "${YELLOW}Stopping and removing app containers and purging existing volumes and images${RESET}"
	$(DOCKER_COMPOSE) down -v --rmi local

app-logs: ## View logs generated by the Flask application
	@tail -f app/logs/flask_app.log

docker-logs: ## View logs generated by Docker containers (optionally specifying a service name, like `python` or `nginx`)
	$(DOCKER_COMPOSE) logs --tail 10 -f $(filter-out $@,$(MAKECMDGOALS))

#==============================================
# Application management commands
#==============================================
lint: ## Run Python code formatter and linter
	@echo "${YELLOW}Linting and auto-formatting Python code${RESET}"
	@black ./app
	@echo "${YELLOW}Checking for PEP8 errors${RESET}"
	@flake8 ./app
lint-check: ## Run Python code formatter and linter in check mode
	@echo "${YELLOW}Linting Python code, leaving as-is${RESET}"
	@black ./app
	@echo "${YELLOW}Checking for PEP8 errors${RESET}"
	@flake8 ./app

.PHONY: help
help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
