upstream flask_app {
	server python:5000;
}

server {
	listen *:80;
	server_name default;

	client_max_body_size 20M;

	location /yaml-to-qti/static/ {
			alias /var/www/html/app/static/;
			expires 30d;
	}

	location /yaml-to-qti {
		try_files $uri @handler;
		expires 30d;
	}

	location @handler {
		proxy_pass http://flask_app;

		proxy_redirect off;
		proxy_set_header Host            $host;
		proxy_set_header X-Real-IP       $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Script-Name /yaml-to-qti;
		proxy_set_header SCRIPT_NAME /yaml-to-qti;
	}
}
